# Generated by Django 3.0.8 on 2020-08-04 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'diseases',
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'symptoms',
                'db_table': 'symptoms',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(verbose_name='Data programari')),
                ('description', models.TextField(help_text='Scurta prezentare de ce doriti aceasta programare ...', verbose_name='Descriere')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'In desfasurare'), (2, 'Incheiat'), (3, 'Anulat')], default=1)),
                ('treatment', models.TextField(blank=True, help_text='Tratament', null=True, verbose_name='Tratament')),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Diseases', verbose_name='Boala')),
            ],
            options={
                'verbose_name_plural': 'appointments',
                'db_table': 'appointments',
            },
        ),
    ]
