# Generated by Django 3.0.8 on 2020-08-04 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='medic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointmentsmedic', to=settings.AUTH_USER_MODEL, verbose_name='Medic'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentspatient', to=settings.AUTH_USER_MODEL, verbose_name='Pacient'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='appointments.Symptoms', verbose_name='Simptome'),
        ),
    ]
